PACKAGE_NAME="hid-shure-mv6"
PACKAGE_VERSION="1.1.0"
MAKE[0]="make module KDIR=/lib/modules/${kernelver}/build"
CLEAN="make module-clean KDIR=/lib/modules/${kernelver}/build"
BUILT_MODULE_NAME[0]="hid-shure-mv6"
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"
